#############################################################################
# Makefile for building: snake
# Generated by qmake (3.1) (Qt 5.9.5)
# Project:  snake.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile snake.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_CHARTS_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -w -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -w -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCharts -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = snake1.0.0
DISTDIR = /home/edgar/interfaces/qt/snake/.tmp/snake1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Charts -lQt5Widgets -lQt5Multimedia -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = Comida.cpp \
		DComidas.cpp \
		DControlPad.cpp \
		DControlSnake.cpp \
		DExamen.cpp \
		DInformacion.cpp \
		DInformacionDetallada.cpp \
		DListaFrutas.cpp \
		DNombreJugador.cpp \
		DPosicionarDos.cpp \
		DPosicionFruta.cpp \
		DPuntuaciones.cpp \
		DSecuenciaFrutas.cpp \
		main.cpp \
		mainWindow.cpp \
		WidgetClick.cpp \
		WidgetComida.cpp \
		WPosicionarDos.cpp moc_DComidas.cpp \
		moc_DControlPad.cpp \
		moc_DControlSnake.cpp \
		moc_DExamen.cpp \
		moc_DInformacion.cpp \
		moc_DInformacionDetallada.cpp \
		moc_DListaFrutas.cpp \
		moc_DNombreJugador.cpp \
		moc_DPosicionarDos.cpp \
		moc_DPosicionFruta.cpp \
		moc_DPuntuaciones.cpp \
		moc_DSecuenciaFrutas.cpp \
		moc_mainWindow.cpp \
		moc_WidgetClick.cpp \
		moc_WidgetComida.cpp \
		moc_WPosicionarDos.cpp
OBJECTS       = Comida.o \
		DComidas.o \
		DControlPad.o \
		DControlSnake.o \
		DExamen.o \
		DInformacion.o \
		DInformacionDetallada.o \
		DListaFrutas.o \
		DNombreJugador.o \
		DPosicionarDos.o \
		DPosicionFruta.o \
		DPuntuaciones.o \
		DSecuenciaFrutas.o \
		main.o \
		mainWindow.o \
		WidgetClick.o \
		WidgetComida.o \
		WPosicionarDos.o \
		moc_DComidas.o \
		moc_DControlPad.o \
		moc_DControlSnake.o \
		moc_DExamen.o \
		moc_DInformacion.o \
		moc_DInformacionDetallada.o \
		moc_DListaFrutas.o \
		moc_DNombreJugador.o \
		moc_DPosicionarDos.o \
		moc_DPosicionFruta.o \
		moc_DPuntuaciones.o \
		moc_DSecuenciaFrutas.o \
		moc_mainWindow.o \
		moc_WidgetClick.o \
		moc_WidgetComida.o \
		moc_WPosicionarDos.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		snake.pro Comida.h \
		DComidas.h \
		DControlPad.h \
		DControlSnake.h \
		DExamen.h \
		DInformacion.h \
		DInformacionDetallada.h \
		DListaFrutas.h \
		DNombreJugador.h \
		DPosicionarDos.h \
		DPosicionFruta.h \
		DPuntuaciones.h \
		DSecuenciaFrutas.h \
		mainWindow.h \
		WidgetClick.h \
		WidgetComida.h \
		WPosicionarDos.h Comida.cpp \
		DComidas.cpp \
		DControlPad.cpp \
		DControlSnake.cpp \
		DExamen.cpp \
		DInformacion.cpp \
		DInformacionDetallada.cpp \
		DListaFrutas.cpp \
		DNombreJugador.cpp \
		DPosicionarDos.cpp \
		DPosicionFruta.cpp \
		DPuntuaciones.cpp \
		DSecuenciaFrutas.cpp \
		main.cpp \
		mainWindow.cpp \
		WidgetClick.cpp \
		WidgetComida.cpp \
		WPosicionarDos.cpp
QMAKE_TARGET  = snake
DESTDIR       = 
TARGET        = snake


first: all
####### Build rules

$(TARGET): ui_DComidas.h ui_DControlPad.h ui_DControlSnake.h ui_DExamen.h ui_DInformacion.h ui_DInformacionDetallada.h ui_DListaFrutas.h ui_DNombreJugador.h ui_DPosicionarDos.h ui_DPosicionFruta.h ui_DPuntuaciones.h ui_DSecuenciaFrutas.h ui_WidgetClick.h ui_WidgetComida.h ui_WidgetImagenFruta.h ui_WPosicionarDos.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: snake.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		snake.pro \
		/usr/lib/x86_64-linux-gnu/libQt5Charts.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Network.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile snake.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_off.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
snake.pro:
/usr/lib/x86_64-linux-gnu/libQt5Charts.prl:
/usr/lib/x86_64-linux-gnu/libQt5Widgets.prl:
/usr/lib/x86_64-linux-gnu/libQt5Multimedia.prl:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Network.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile snake.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents Comida.h DComidas.h DControlPad.h DControlSnake.h DExamen.h DInformacion.h DInformacionDetallada.h DListaFrutas.h DNombreJugador.h DPosicionarDos.h DPosicionFruta.h DPuntuaciones.h DSecuenciaFrutas.h mainWindow.h WidgetClick.h WidgetComida.h WPosicionarDos.h $(DISTDIR)/
	$(COPY_FILE) --parents Comida.cpp DComidas.cpp DControlPad.cpp DControlSnake.cpp DExamen.cpp DInformacion.cpp DInformacionDetallada.cpp DListaFrutas.cpp DNombreJugador.cpp DPosicionarDos.cpp DPosicionFruta.cpp DPuntuaciones.cpp DSecuenciaFrutas.cpp main.cpp mainWindow.cpp WidgetClick.cpp WidgetComida.cpp WPosicionarDos.cpp $(DISTDIR)/
	$(COPY_FILE) --parents DComidas.ui DControlPad.ui DControlSnake.ui DExamen.ui DInformacion.ui DInformacionDetallada.ui DListaFrutas.ui DNombreJugador.ui DPosicionarDos.ui DPosicionFruta.ui DPuntuaciones.ui DSecuenciaFrutas.ui WidgetClick.ui WidgetComida.ui WidgetImagenFruta.ui WPosicionarDos.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -w -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_DComidas.cpp moc_DControlPad.cpp moc_DControlSnake.cpp moc_DExamen.cpp moc_DInformacion.cpp moc_DInformacionDetallada.cpp moc_DListaFrutas.cpp moc_DNombreJugador.cpp moc_DPosicionarDos.cpp moc_DPosicionFruta.cpp moc_DPuntuaciones.cpp moc_DSecuenciaFrutas.cpp moc_mainWindow.cpp moc_WidgetClick.cpp moc_WidgetComida.cpp moc_WPosicionarDos.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_DComidas.cpp moc_DControlPad.cpp moc_DControlSnake.cpp moc_DExamen.cpp moc_DInformacion.cpp moc_DInformacionDetallada.cpp moc_DListaFrutas.cpp moc_DNombreJugador.cpp moc_DPosicionarDos.cpp moc_DPosicionFruta.cpp moc_DPuntuaciones.cpp moc_DSecuenciaFrutas.cpp moc_mainWindow.cpp moc_WidgetClick.cpp moc_WidgetComida.cpp moc_WPosicionarDos.cpp
moc_DComidas.cpp: ui_DComidas.h \
		Comida.h \
		WidgetComida.h \
		ui_WidgetComida.h \
		DComidas.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DComidas.h -o moc_DComidas.cpp

moc_DControlPad.cpp: ui_DControlPad.h \
		DControlPad.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DControlPad.h -o moc_DControlPad.cpp

moc_DControlSnake.cpp: ui_DControlSnake.h \
		DControlSnake.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DControlSnake.h -o moc_DControlSnake.cpp

moc_DExamen.cpp: ui_DExamen.h \
		DExamen.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DExamen.h -o moc_DExamen.cpp

moc_DInformacion.cpp: ui_DInformacion.h \
		DInformacion.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DInformacion.h -o moc_DInformacion.cpp

moc_DInformacionDetallada.cpp: ui_DInformacionDetallada.h \
		DInformacionDetallada.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DInformacionDetallada.h -o moc_DInformacionDetallada.cpp

moc_DListaFrutas.cpp: ui_DListaFrutas.h \
		Comida.h \
		DListaFrutas.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DListaFrutas.h -o moc_DListaFrutas.cpp

moc_DNombreJugador.cpp: ui_DNombreJugador.h \
		DNombreJugador.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DNombreJugador.h -o moc_DNombreJugador.cpp

moc_DPosicionarDos.cpp: ui_DPosicionarDos.h \
		WPosicionarDos.h \
		ui_WPosicionarDos.h \
		DPosicionarDos.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DPosicionarDos.h -o moc_DPosicionarDos.cpp

moc_DPosicionFruta.cpp: ui_DPosicionFruta.h \
		WidgetClick.h \
		ui_WidgetClick.h \
		DPosicionFruta.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DPosicionFruta.h -o moc_DPosicionFruta.cpp

moc_DPuntuaciones.cpp: ui_DPuntuaciones.h \
		DPuntuaciones.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DPuntuaciones.h -o moc_DPuntuaciones.cpp

moc_DSecuenciaFrutas.cpp: ui_DSecuenciaFrutas.h \
		ui_WidgetImagenFruta.h \
		Comida.h \
		DSecuenciaFrutas.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include DSecuenciaFrutas.h -o moc_DSecuenciaFrutas.cpp

moc_mainWindow.cpp: DNombreJugador.h \
		ui_DNombreJugador.h \
		DPuntuaciones.h \
		ui_DPuntuaciones.h \
		DControlPad.h \
		ui_DControlPad.h \
		Comida.h \
		DComidas.h \
		ui_DComidas.h \
		WidgetComida.h \
		ui_WidgetComida.h \
		DPosicionFruta.h \
		ui_DPosicionFruta.h \
		WidgetClick.h \
		ui_WidgetClick.h \
		DSecuenciaFrutas.h \
		ui_DSecuenciaFrutas.h \
		ui_WidgetImagenFruta.h \
		DPosicionarDos.h \
		ui_DPosicionarDos.h \
		WPosicionarDos.h \
		ui_WPosicionarDos.h \
		DListaFrutas.h \
		ui_DListaFrutas.h \
		DInformacion.h \
		ui_DInformacion.h \
		DControlSnake.h \
		ui_DControlSnake.h \
		DInformacionDetallada.h \
		ui_DInformacionDetallada.h \
		mainWindow.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include mainWindow.h -o moc_mainWindow.cpp

moc_WidgetClick.cpp: ui_WidgetClick.h \
		WidgetClick.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include WidgetClick.h -o moc_WidgetClick.cpp

moc_WidgetComida.cpp: ui_WidgetComida.h \
		Comida.h \
		WidgetComida.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include WidgetComida.h -o moc_WidgetComida.cpp

moc_WPosicionarDos.cpp: ui_WPosicionarDos.h \
		WPosicionarDos.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include ./moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/edgar/interfaces/qt/snake -I/home/edgar/interfaces/qt/snake -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCharts -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtMultimedia -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include WPosicionarDos.h -o moc_WPosicionarDos.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_DComidas.h ui_DControlPad.h ui_DControlSnake.h ui_DExamen.h ui_DInformacion.h ui_DInformacionDetallada.h ui_DListaFrutas.h ui_DNombreJugador.h ui_DPosicionarDos.h ui_DPosicionFruta.h ui_DPuntuaciones.h ui_DSecuenciaFrutas.h ui_WidgetClick.h ui_WidgetComida.h ui_WidgetImagenFruta.h ui_WPosicionarDos.h
compiler_uic_clean:
	-$(DEL_FILE) ui_DComidas.h ui_DControlPad.h ui_DControlSnake.h ui_DExamen.h ui_DInformacion.h ui_DInformacionDetallada.h ui_DListaFrutas.h ui_DNombreJugador.h ui_DPosicionarDos.h ui_DPosicionFruta.h ui_DPuntuaciones.h ui_DSecuenciaFrutas.h ui_WidgetClick.h ui_WidgetComida.h ui_WidgetImagenFruta.h ui_WPosicionarDos.h
ui_DComidas.h: DComidas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DComidas.ui -o ui_DComidas.h

ui_DControlPad.h: DControlPad.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DControlPad.ui -o ui_DControlPad.h

ui_DControlSnake.h: DControlSnake.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DControlSnake.ui -o ui_DControlSnake.h

ui_DExamen.h: DExamen.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DExamen.ui -o ui_DExamen.h

ui_DInformacion.h: DInformacion.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DInformacion.ui -o ui_DInformacion.h

ui_DInformacionDetallada.h: DInformacionDetallada.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DInformacionDetallada.ui -o ui_DInformacionDetallada.h

ui_DListaFrutas.h: DListaFrutas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DListaFrutas.ui -o ui_DListaFrutas.h

ui_DNombreJugador.h: DNombreJugador.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DNombreJugador.ui -o ui_DNombreJugador.h

ui_DPosicionarDos.h: DPosicionarDos.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DPosicionarDos.ui -o ui_DPosicionarDos.h

ui_DPosicionFruta.h: DPosicionFruta.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DPosicionFruta.ui -o ui_DPosicionFruta.h

ui_DPuntuaciones.h: DPuntuaciones.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DPuntuaciones.ui -o ui_DPuntuaciones.h

ui_DSecuenciaFrutas.h: DSecuenciaFrutas.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic DSecuenciaFrutas.ui -o ui_DSecuenciaFrutas.h

ui_WidgetClick.h: WidgetClick.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic WidgetClick.ui -o ui_WidgetClick.h

ui_WidgetComida.h: WidgetComida.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic WidgetComida.ui -o ui_WidgetComida.h

ui_WidgetImagenFruta.h: WidgetImagenFruta.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic WidgetImagenFruta.ui -o ui_WidgetImagenFruta.h

ui_WPosicionarDos.h: WPosicionarDos.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic WPosicionarDos.ui -o ui_WPosicionarDos.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

Comida.o: Comida.cpp Comida.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Comida.o Comida.cpp

DComidas.o: DComidas.cpp DComidas.h \
		ui_DComidas.h \
		Comida.h \
		WidgetComida.h \
		ui_WidgetComida.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DComidas.o DComidas.cpp

DControlPad.o: DControlPad.cpp DControlPad.h \
		ui_DControlPad.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DControlPad.o DControlPad.cpp

DControlSnake.o: DControlSnake.cpp DControlSnake.h \
		ui_DControlSnake.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DControlSnake.o DControlSnake.cpp

DExamen.o: DExamen.cpp DExamen.h \
		ui_DExamen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DExamen.o DExamen.cpp

DInformacion.o: DInformacion.cpp DInformacion.h \
		ui_DInformacion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DInformacion.o DInformacion.cpp

DInformacionDetallada.o: DInformacionDetallada.cpp DInformacionDetallada.h \
		ui_DInformacionDetallada.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DInformacionDetallada.o DInformacionDetallada.cpp

DListaFrutas.o: DListaFrutas.cpp DListaFrutas.h \
		ui_DListaFrutas.h \
		Comida.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DListaFrutas.o DListaFrutas.cpp

DNombreJugador.o: DNombreJugador.cpp DNombreJugador.h \
		ui_DNombreJugador.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DNombreJugador.o DNombreJugador.cpp

DPosicionarDos.o: DPosicionarDos.cpp DPosicionarDos.h \
		ui_DPosicionarDos.h \
		WPosicionarDos.h \
		ui_WPosicionarDos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DPosicionarDos.o DPosicionarDos.cpp

DPosicionFruta.o: DPosicionFruta.cpp DPosicionFruta.h \
		ui_DPosicionFruta.h \
		WidgetClick.h \
		ui_WidgetClick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DPosicionFruta.o DPosicionFruta.cpp

DPuntuaciones.o: DPuntuaciones.cpp DPuntuaciones.h \
		ui_DPuntuaciones.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DPuntuaciones.o DPuntuaciones.cpp

DSecuenciaFrutas.o: DSecuenciaFrutas.cpp DSecuenciaFrutas.h \
		ui_DSecuenciaFrutas.h \
		ui_WidgetImagenFruta.h \
		Comida.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DSecuenciaFrutas.o DSecuenciaFrutas.cpp

main.o: main.cpp mainWindow.h \
		DNombreJugador.h \
		ui_DNombreJugador.h \
		DPuntuaciones.h \
		ui_DPuntuaciones.h \
		DControlPad.h \
		ui_DControlPad.h \
		Comida.h \
		DComidas.h \
		ui_DComidas.h \
		WidgetComida.h \
		ui_WidgetComida.h \
		DPosicionFruta.h \
		ui_DPosicionFruta.h \
		WidgetClick.h \
		ui_WidgetClick.h \
		DSecuenciaFrutas.h \
		ui_DSecuenciaFrutas.h \
		ui_WidgetImagenFruta.h \
		DPosicionarDos.h \
		ui_DPosicionarDos.h \
		WPosicionarDos.h \
		ui_WPosicionarDos.h \
		DListaFrutas.h \
		ui_DListaFrutas.h \
		DInformacion.h \
		ui_DInformacion.h \
		DControlSnake.h \
		ui_DControlSnake.h \
		DInformacionDetallada.h \
		ui_DInformacionDetallada.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainWindow.o: mainWindow.cpp mainWindow.h \
		DNombreJugador.h \
		ui_DNombreJugador.h \
		DPuntuaciones.h \
		ui_DPuntuaciones.h \
		DControlPad.h \
		ui_DControlPad.h \
		Comida.h \
		DComidas.h \
		ui_DComidas.h \
		WidgetComida.h \
		ui_WidgetComida.h \
		DPosicionFruta.h \
		ui_DPosicionFruta.h \
		WidgetClick.h \
		ui_WidgetClick.h \
		DSecuenciaFrutas.h \
		ui_DSecuenciaFrutas.h \
		ui_WidgetImagenFruta.h \
		DPosicionarDos.h \
		ui_DPosicionarDos.h \
		WPosicionarDos.h \
		ui_WPosicionarDos.h \
		DListaFrutas.h \
		ui_DListaFrutas.h \
		DInformacion.h \
		ui_DInformacion.h \
		DControlSnake.h \
		ui_DControlSnake.h \
		DInformacionDetallada.h \
		ui_DInformacionDetallada.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainWindow.o mainWindow.cpp

WidgetClick.o: WidgetClick.cpp WidgetClick.h \
		ui_WidgetClick.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WidgetClick.o WidgetClick.cpp

WidgetComida.o: WidgetComida.cpp WidgetComida.h \
		ui_WidgetComida.h \
		Comida.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WidgetComida.o WidgetComida.cpp

WPosicionarDos.o: WPosicionarDos.cpp WPosicionarDos.h \
		ui_WPosicionarDos.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o WPosicionarDos.o WPosicionarDos.cpp

moc_DComidas.o: moc_DComidas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DComidas.o moc_DComidas.cpp

moc_DControlPad.o: moc_DControlPad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DControlPad.o moc_DControlPad.cpp

moc_DControlSnake.o: moc_DControlSnake.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DControlSnake.o moc_DControlSnake.cpp

moc_DExamen.o: moc_DExamen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DExamen.o moc_DExamen.cpp

moc_DInformacion.o: moc_DInformacion.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DInformacion.o moc_DInformacion.cpp

moc_DInformacionDetallada.o: moc_DInformacionDetallada.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DInformacionDetallada.o moc_DInformacionDetallada.cpp

moc_DListaFrutas.o: moc_DListaFrutas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DListaFrutas.o moc_DListaFrutas.cpp

moc_DNombreJugador.o: moc_DNombreJugador.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DNombreJugador.o moc_DNombreJugador.cpp

moc_DPosicionarDos.o: moc_DPosicionarDos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DPosicionarDos.o moc_DPosicionarDos.cpp

moc_DPosicionFruta.o: moc_DPosicionFruta.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DPosicionFruta.o moc_DPosicionFruta.cpp

moc_DPuntuaciones.o: moc_DPuntuaciones.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DPuntuaciones.o moc_DPuntuaciones.cpp

moc_DSecuenciaFrutas.o: moc_DSecuenciaFrutas.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DSecuenciaFrutas.o moc_DSecuenciaFrutas.cpp

moc_mainWindow.o: moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainWindow.o moc_mainWindow.cpp

moc_WidgetClick.o: moc_WidgetClick.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WidgetClick.o moc_WidgetClick.cpp

moc_WidgetComida.o: moc_WidgetComida.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WidgetComida.o moc_WidgetComida.cpp

moc_WPosicionarDos.o: moc_WPosicionarDos.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_WPosicionarDos.o moc_WPosicionarDos.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

